### ISSUE TITLE
Repositories without stars are missing in “Top Repositories by Stars“ bar chart

### ISSUE THREAD

**Issue by markuspoerschke** [sourcectl/feedback#3]
**What happened**:

I visited my [_Stars Dashboard_](https://app.sourcectl.dev/a/markuspoerschke/stars) and looked at the _Top Repository by Stars_ widget. One of my repositories having 0 stars.

![image](https://user-images.githubusercontent.com/1222377/114590365-f849bf00-9c88-11eb-9904-0f995ebed155.png)

In the screenshot you can see that the repository named “markuspoerschke/extractum“ has zero stars and it is missing in the bar chart above.

**What you expected to happen**:

The widget _Top Repository by Stars_ should show all repositories. Even repositories that do not have stars should appear there.

**Anything else we need to know?**:

**Comment by andygrunwald** [comment]
Hey @markuspoerschke,
thanks for the ticket!
A few minutes ago, I deployed a new version where this bug should be fixed.
Can you re-visit https://app.sourcectl.dev/ and confirm that the repositories without stars are now visible?

**Comment by markuspoerschke** [comment]
It works. 👍🏻 

I close the ticket, because the bug was fixed.
