### ISSUE TITLE
“Last 2 weeks (unique)“ metrics are missing

### ISSUE THREAD

**Issue by markuspoerschke** [sourcectl/feedback#4]
**What happened**:

I visit the _Repository Traffic Dashboard_. In the table I can see the column "Last 2 Weeks (unique)". It shows zero visits, even though I had 2,400 visits last month. It is not plausible that I have not had a single visit within the last two weeks because I had visits last week.

![image](https://user-images.githubusercontent.com/1222377/114591087-cdac3600-9c89-11eb-9fc6-198dd3977695.png)

**What you expected to happen**:

The column "Last 2 Weeks (unique)" should indicate the correct number of visits.

**Comment by markuspoerschke** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/1222377/114983842-62cd4b80-9e91-11eb-9590-79be6e012ec9.png">

I visted the page today again. To me the problem is non existent anymore.

**Comment by andygrunwald** [comment]
This seems to be an unlucky timing issue in gathering the data.
I maybe should add a piece of information into the screen that the data gathering is still ongoing.

Thanks for following up.
